# Sass Lint Documentation: https://github.com/sasstools/sass-lint
files:
    include:
        - 'sass/**/*.s+(a|c)ss'
        - 'www/sass/**/*.s+(a|c)ss'
    ignore:
        - 'www/sass/bourbon/**'
        - 'www/sass/neat/**'
        - '**/_fontface.scss'
rules:
    # Extends
    extends-before-mixins: 0
    extends-before-declarations: 1
    placeholder-in-extend: 0

    # Mixins
    mixins-before-declarations:
        - 1
        -
            exclude: ['media'] # except @include media();

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks: 1
    single-line-per-selector: 1

    # Disallows
    no-color-keywords: 1
    no-color-literals:
        - 1
        -
            allow-rgba: true
    no-css-comments: 1
    no-debug: 0
    no-duplicate-properties: 0
    no-empty-rulesets: 0
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 0
    no-misspelled-properties: 1
    no-qualifying-elements: 0
    no-trailing-zero: 0
    no-transition-all: 0
    no-url-protocols: 0
    no-vendor-prefixes: 0
    no-warn: 0

    # Nesting
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    function-name-format: 0
    mixin-name-format: 0
    placeholder-name-format: 0
    variable-name-format:
        - 0
        -
            allow-leading-underscore: false

    # Style Guide
    border-zero: 0
    brace-style:
        - 1
        -
            style: 1tbs
            allow-single-line: false
    class-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: strictbem
            ignore: []

    clean-import-paths: 0
    empty-args: 0
    hex-length: 0
    hex-notation:
        - 1
        -
            style: lowercase

    indentation:
        - 2
        -
            size: 4
    leading-zero:
        - 1
        -
            include: true

    nesting-depth:
        - 1
        -
            max-depth: 4

    property-units:
        - 1
        -
            per-property: {}

    property-sort-order: 2
    quotes:
        - 2
        -
            style: single

    shorthand-values:
        - 1
        -
            allowed-shorthands:
                - 1
                - 2

    url-quotes: 0
    variable-for-property:
        - 2
        -
            properties: ['color']

    zero-unit: 1

    # Inner Spacing
    space-after-comma: 2
    space-before-colon: 0
    space-after-colon: 2
    space-before-brace: 1
    space-before-bang: 2
    space-after-bang: 0
    space-around-operator:
        - 1
        -
            include: true

    space-between-parens: 0

    # Final Items
    trailing-semicolon: 1
    final-newline: 2
