module.exports = [{
    id: 'AL',
    contiguous: true,
    name: 'Alabama',
    fips: '01'
}, {
    id: 'AK',
    contiguous: false,
    name: 'Alaska',
    fips: '02'
}, {
    id: 'AZ',
    contiguous: true,
    name: 'Arizona',
    fips: '04'
}, {
    id: 'AR',
    contiguous: true,
    name: 'Arkansas',
    fips: '05'
}, {
    id: 'CA',
    contiguous: true,
    name: 'California',
    fips: '06'
}, {
    id: 'CO',
    contiguous: true,
    name: 'Colorado',
    fips: '08'
}, {
    id: 'CT',
    contiguous: true,
    name: 'Connecticut',
    fips: '09'
}, {
    id: 'DE',
    contiguous: true,
    name: 'Delaware',
    fips: '10'
}, {
    id: 'DC',
    contiguous: true,
    name: 'District of Columbia',
    fips: '11'
}, {
    id: 'FL',
    contiguous: true,
    name: 'Florida',
    fips: '12'
}, {
    id: 'GA',
    contiguous: true,
    name: 'Georgia',
    fips: '13'
}, {
    id: 'HI',
    contiguous: false,
    name: 'Hawaii',
    fips: '15'
}, {
    id: 'ID',
    contiguous: true,
    name: 'Idaho',
    fips: '16'
}, {
    id: 'IL',
    contiguous: true,
    name: 'Illinois',
    fips: '17'
}, {
    id: 'IN',
    contiguous: true,
    name: 'Indiana',
    fips: '18'
}, {
    id: 'IA',
    contiguous: true,
    name: 'Iowa',
    fips: '19'
}, {
    id: 'KS',
    contiguous: true,
    name: 'Kansas',
    fips: '20'
}, {
    id: 'KY',
    contiguous: true,
    name: 'Kentucky',
    fips: '21'
}, {
    id: 'LA',
    contiguous: true,
    name: 'Louisiana',
    fips: '22'
}, {
    id: 'ME',
    contiguous: true,
    name: 'Maine',
    fips: '23'
}, {
    id: 'MD',
    contiguous: true,
    name: 'Maryland',
    fips: '24'
}, {
    id: 'MA',
    contiguous: true,
    name: 'Massachusetts',
    fips: '25'
}, {
    id: 'MI',
    contiguous: true,
    name: 'Michigan',
    fips: '26'
}, {
    id: 'MN',
    contiguous: true,
    name: 'Minnesota',
    fips: '27'
}, {
    id: 'MS',
    contiguous: true,
    name: 'Mississsippi',
    fips: '28'
}, {
    id: 'MO',
    contiguous: true,
    name: 'Missouri',
    fips: '29'
}, {
    id: 'MT',
    contiguous: true,
    name: 'Montana',
    fips: '30'
}, {
    id: 'NE',
    contiguous: true,
    name: 'Nebraska',
    fips: '31'
}, {
    id: 'NV',
    contiguous: true,
    name: 'Nevada',
    fips: '32'
}, {
    id: 'NH',
    contiguous: true,
    name: 'New Hampshire',
    fips: '33'
}, {
    id: 'NJ',
    contiguous: true,
    name: 'New Jersey',
    fips: '34'
}, {
    id: 'NM',
    contiguous: true,
    name: 'New Mexico',
    fips: '35'
}, {
    id: 'NY',
    contiguous: true,
    name: 'New York',
    fips: '36'
}, {
    id: 'NC',
    contiguous: true,
    name: 'North Carolina',
    fips: '37'
}, {
    id: 'ND',
    contiguous: true,
    name: 'North Dakota',
    fips: '38'
}, {
    id: 'OH',
    contiguous: true,
    name: 'Ohio',
    fips: '39'
}, {
    id: 'OK',
    contiguous: true,
    name: 'Oklahoma',
    fips: '40'
}, {
    id: 'OR',
    contiguous: true,
    name: 'Oregon',
    fips: '41'
}, {
    id: 'PA',
    contiguous: true,
    name: 'Pennsylvania',
    fips: '42'
}, {
    id: 'PR',
    contiguous: false,
    name: 'Puerto Rico',
    fips: '72'
}, {
    id: 'RI',
    contiguous: true,
    name: 'Rhode Island',
    fips: '44'
}, {
    id: 'SC',
    contiguous: true,
    name: 'South Carolina',
    fips: '45'
}, {
    id: 'SD',
    contiguous: true,
    name: 'South Dakota',
    fips: '46'
}, {
    id: 'TN',
    contiguous: true,
    name: 'Tennessee',
    fips: '47'
}, {
    id: 'TX',
    contiguous: true,
    name: 'Texas',
    fips: '48'
}, {
    id: 'UT',
    contiguous: true,
    name: 'Utah',
    fips: '49'
}, {
    id: 'VT',
    contiguous: true,
    name: 'Vermont',
    fips: '50'
}, {
    id: 'VA',
    contiguous: true,
    name: 'Virginia',
    fips: '51'
}, {
    id: 'WA',
    contiguous: true,
    name: 'Washington',
    fips: '53'
}, {
    id: 'WV',
    contiguous: true,
    name: 'West Virginia',
    fips: '54'
}, {
    id: 'WI',
    contiguous: true,
    name: 'Wisconsin',
    fips: '55'
}, {
    id: 'WY',
    contiguous: true,
    name: 'Wyoming',
    fips: '56'
}];
